name: Moodle Plugin CI

on: 
  push:
    paths:
      - '**/*.php'  # Exécuter la CI uniquement si des fichiers PHP sont modifiés
  pull_request:
    paths:
      - '**/*.php'  # Exécuter la CI uniquement si des fichiers PHP sont modifiés

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        php: ['8.0']
        moodle-branch: ['MOODLE_401_STABLE']
        database: [mariadb]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Vérifier si les conteneurs Moodle & MariaDB existent
        run: |
          echo "🔍 Vérification des conteneurs..."
          docker ps | grep "moodle" && echo "✅ Moodle est actif." || { echo "❌ Moodle n'est pas actif !"; exit 1; }
          docker ps | grep "mariadb" && echo "✅ MariaDB est actif." || { echo "❌ MariaDB n'est pas actif !"; exit 1; }

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: max_input_vars=5000
          coverage: none
        

      - name: Cache PHP extensions
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-php-${{ matrix.php }}-extensions-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-extensions-

      - name: Vérifier la version PHP installée
        run: |
          php -v
          # Vérification si la version PHP est compatible avec php-cs-fixer
          if ! php -m | grep -q "json"; then
            echo "⚠️ La bibliothèque JSON est manquante !"
            exit 1
          fi

      - name: Initialiser moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo "$(cd ci/bin; pwd)" >> $GITHUB_PATH
          echo "$(cd ci/vendor/bin; pwd)" >> $GITHUB_PATH
          sudo apt-get install -y locales
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

      - name: Mettre à jour les dépendances composer
        run: composer update --no-dev

      - name: Installer PHP-CS-Fixer
        run: |
          composer require --dev friendsofphp/php-cs-fixer:^2.0

      - name: Vérifier les fichiers modifiés
        id: check_modified
        run: |
          echo "🔍 Vérification des fichiers modifiés..."
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          echo "Fichiers modifiés : $(cat changed_files.txt)"
          echo "::set-output name=files::$(cat changed_files.txt)"

      - name: Formater le code avec PHP-CS-Fixer (uniquement pour les fichiers modifiés)
        run: |
          CHANGED_FILES="${{ steps.check_modified.outputs.files }}"
          if echo "$CHANGED_FILES" | grep -qE '\.php$'; then
            echo "📋 Formatage des fichiers PHP modifiés..."
            vendor/bin/php-cs-fixer fix $CHANGED_FILES --rules=@Moodle --verbose
          else
            echo "Aucun fichier PHP modifié, saut du formatage."
          fi

      - name: Exécuter PHPUnit Tests (uniquement pour les fichiers modifiés)
        if: ${{ steps.check_modified.outputs.files != '' }}
        run: |
          CHANGED_FILES="${{ steps.check_modified.outputs.files }}"
          if echo "$CHANGED_FILES" | grep -qE '\.php$'; then
            echo "🧪 Exécution des tests PHPUnit pour les fichiers modifiés..."
            moodle-plugin-ci phpunit ./moodle/mod/studentqcm --fail-on-warning
          else
            echo "Aucun fichier PHP modifié, saut des tests PHPUnit."
          fi

      - name: Exécuter Behat Features (Chrome)
        id: behat
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci behat ./moodle/mod/studentqcm --profile chrome

      - name: Upload Behat Faildump en cas d'échec
        if: ${{ failure() && steps.behat.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: Behat Faildump (${{ join(matrix.*, ', ') }})
          path: ${{ github.workspace }}/moodledata/behat_dump
          retention-days: 7
          if-no-files-found: ignore

      - name: Mark cancelled jobs as failed
        if: ${{ cancelled() }}
        run: exit 1
